// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../tyts/protobuf.js', ['tyts.ProtoBuf', 'tyts.SizeVarint', 'tyts.WireBytes', 'tyts.WireEnd', 'tyts.WireFixed32', 'tyts.WireFixed64', 'tyts.WireStart', 'tyts.WireTypeBits', 'tyts.WireTypeMask', 'tyts.WireVarint'], [], false);
goog.addDependency('../../../../tyts/test/extension.js', ['GoType'], [], false);
goog.addDependency('../../../../tyts/test/types.js', ['Fighter', 'Fighter_Part1', 'Fighter_Part2', 'Vector2'], ['GoType', 'tyts.Bool', 'tyts.Bytes', 'tyts.Dict', 'tyts.Extension', 'tyts.FixedPoint', 'tyts.Float32', 'tyts.Float64', 'tyts.Integer', 'tyts.List', 'tyts.Method', 'tyts.Object', 'tyts.String', 'tyts.Variant'], false);
goog.addDependency('../../../../tyts/tyts.js', ['tyts.Bool', 'tyts.Bytes', 'tyts.Dict', 'tyts.Extension', 'tyts.FixedPoint', 'tyts.Float32', 'tyts.Float64', 'tyts.Integer', 'tyts.List', 'tyts.Method', 'tyts.Object', 'tyts.String', 'tyts.Variant'], ['tyts.ProtoBuf', 'tyts.SizeVarint', 'tyts.WireBytes', 'tyts.WireFixed32', 'tyts.WireFixed64', 'tyts.WireTypeBits', 'tyts.WireTypeMask', 'tyts.WireVarint'], false);
